# Generated by Django 5.2.12 on 2026-04-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("editor", "Editor"),
                    ("journalist", "Journalist"),
                    ("publisher", "Publisher"),
                ],
                max_length=20,
            ),
        ),
    ]
